version: '3.9'

services:  
  app:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - NOTION_DATE_FIELD=${NOTION_DATE_FIELD}
      - REDIS_HOST=redis
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
